version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-algoedge}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-algoedge}
      POSTGRES_DB: ${POSTGRES_DB:-algoedge}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-algoedge}:${POSTGRES_PASSWORD:-algoedge}@postgres:5432/${POSTGRES_DB:-algoedge}
      REDIS_URL: redis://redis:6379/0
      PYTHONUNBUFFERED: "1"
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-algoedge}:${POSTGRES_PASSWORD:-algoedge}@postgres:5432/${POSTGRES_DB:-algoedge}
      REDIS_URL: redis://redis:6379/0
      PYTHONUNBUFFERED: "1"
    depends_on:
      - postgres
      - redis

  web:
    build: ./apps/web
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata: